---
title: "temporal"
author: "Jake Eisaguirre"
date: "3/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries 
```{r}
library(tidyverse)
library(ggplot2)
library(here)
library(janitor)
library(lubridate)
library(stringr)
library(plotly)
 
```


# COT
```{r}
# read in data
cots <- read_csv(here("data/csv/COT_abundance.csv")) %>%
  clean_names()

cots$year <- as.factor(cots$year)
# summary df
cots_summary <- cots %>%
  group_by(site, year) %>%
  summarize(total = sum(cots))

cots_counts <- ggplot(data = cots_summary, aes(x = as.factor(year), y = total, fill = site)) +
  geom_col(position = "stack") +
  labs(title = "Crown of Thorns Sea Stars",
       subtitle = "Moorea, French Polynesia (2005-2018)",
       fill = "Site",
       x = "Year",
       y = "Total") +
  scale_y_continuous(breaks = seq(0, 150, by = 25)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 16)) +
  #scale_fill_brewer(palette = “Set2") +
  scale_fill_manual(values = c("#40B5AD", "#87CEEB", "#4682B4", "#6F8FAF", "#9FE2BF", "#6495ED")) +
  geom_text(
    aes(label = stat(y), group = year),
    stat = "summary", fun = sum, vjust = -1, nudge_y = 2)
ggplotly(cots_counts,
         tooltip = c("total", "site"))  %>%
  layout(title = list(text = paste0("Crown of Thorns Sea Stars",
                                    "<br>",
                                    "<sup>",
                                    "Moorea, French Polynesia (2005-2018)",
                                    "</sup>")))
# DENSITY PLOT
# densities by site
# group by site & year , sum total observations / 1000 -> annual site density
# 4 5x50 m transects per site
cots_density <-  cots %>%
  group_by(site, year) %>%
  summarize(density = (sum(cots)/1000)) # this should give annual site density/ m^2

# density plot
ggplot(data = cots_density, aes(x = year, y = density)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site)) +
  facet_wrap(~site) +
  labs(title = 'Crown of Thorns Sea Stars - Annual Site Densities',
       subtitle = 'Moorea, French Polynesia (2005 - 2018)',
       y = 'Density (count/m^2)',
       x = 'Year',
       color = 'Site') +
  #scale_x_discrete(labels = c(“”, 2006, “”, 2008, “”, 2010, “”, 2012, “”, 2014, “”, 2016, “”, 2018)) +
  scale_color_manual(values = c('#40B5AD', '#87CEEB', '#4682B4', '#6F8FAF', '#9FE2BF', '#6495ED')) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.x = element_text(size=14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(size = 16))
```

# percent coral cover - Double check coral species list
```{r}

coral_cover_raw <- read_csv(here("data", "csv", "percent_coral_cover.csv")) %>%
  clean_names()

coral_cover <- coral_cover_raw %>%
  as.data.frame() %>% 
  select(date, site, taxonomy_substrate_or_functional_group, percent_cover) %>% 
  filter(!str_detect(percent_cover, "ND")) %>% 
  filter(!str_detect(percent_cover, "0.0")) %>% 
  filter(!taxonomy_substrate_or_functional_group %in% 
           c("Sand", "Non-coralline Crustose Algae", "Unknown or Other",
             "CTB", "Macroalgae")) %>% 
  mutate(date = str_sub(date, 1, -4)) %>% 
  mutate(date = as.numeric(date),
         percent_cover = as.numeric(percent_cover))

sum_coral_cover <- coral_cover %>% 
  group_by(site, date) %>% 
  summarize(mean_coral_cover = (mean(percent_cover) * 4))
  
  
ggplot(sum_coral_cover) +
  geom_line(aes(x = date, y = mean_coral_cover, group = site, color = site)) +
  xlab("Year") +
  ylab(expression(paste("Average Percent Coral Cover per 0.25 ", m^{2}))) +
  theme_classic()
  



```

# herbivore biomass
```{r}
# read in data and clean
fish_biomass <- read_csv(here("data/csv/fish.csv")) %>%
  clean_names()

fish_biomass$site <- as.factor(fish_biomass$site)
# We only want “LTER #”
# Below I used substr() function to find first n characters of the column in R. substr() function takes column name, starting position and length of the strings as argument, which will return the substring of the specific column as shown below.

fish_biomass$substring_location =
  substr(fish_biomass$location,1,6)
# Create ‘year’, ‘site’, and ‘biomass’ column
biomass_summary <- fish_biomass %>%
  filter(coarse_trophic == "Primary Consumer") %>%
  select(year, "site" = substring_location, biomass) %>%
  group_by(year, site) %>%
  summarize(mean = mean(biomass))

ggplot(data = biomass_summary, aes(x = year, y = mean)) +
  geom_point(aes(color = site)) +
  geom_line(aes(group = site, color = site))
```

# percent algae
```{r}
algae_cover_raw <- read_csv(here("data", "csv", "percent_algae_cover.csv")) %>%
  clean_names()

algae_cover <- algae_cover_raw %>% 
  select(year, site, taxonomy_substrate_functional_group, percent_cover) %>% 
  filter(!taxonomy_substrate_functional_group %in% 
           c("Sand", "Coral", "Bare Space", "Millepora platyphylla", "Soft Coral",
             "No data", "NA", "Sponge", "Shell Debris", "Coral Rubble")) %>% 
  filter(!str_detect(percent_cover, "0"))

sum_algae_cover <- algae_cover %>% 
  group_by(year, site) %>% 
  summarize(mean_algae_cover = mean(percent_cover))

ggplot(sum_algae_cover) +
  geom_line(aes(x = year, y = mean_algae_cover, group = site, color = site)) +
  xlab("Year") +
  ylab(expression(paste("Average Percent Algae Cover per 0.25 ", m^{2}))) +
  theme_classic()

```


