---
title: "final_visualization"
author: "Charles Hendrickson"
date: "3/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# load packages
librarian::shelf(ggplot2,lubridate, tidyverse, janitor, plotly, fishualize)
```


The data is from the Environmental Data Initiative data portal. https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-mcr.6.61

The Anual Fish Survey data contains fish transect visual counts repeated annually include species, fish length, estimated biomass, and trophic group.
```{r}
# load data
annual_fish_survey_data <- read.csv("data/MCR_LTER_Annual_Fish_Survey_20220119.csv")

percent_cover_data <- read.csv("data/knb-lter-mcr.4_2_20190321.csv")

```


Clean data column names and change data type of the column 'site' from numeric to a factor
```{r}
# make all column names lowercase 
annual_fish_survey_data <- annual_fish_survey_data %>%
  clean_names()

percent_cover_data <- percent_cover_data %>% 
  clean_names()

# Change data type of the column 'site' from numeric to a factor
annual_fish_survey_data$site <- as.factor(annual_fish_survey_data$site)
```


```{r}
# We only want "LTER #" 
# Below I used substr() function to find first n characters of the column in R. substr() function takes column name, starting position and length of the strings as argument, which will return the substring of the specific column as shown below.

annual_fish_survey_data$substring_location = 
  substr(annual_fish_survey_data$location,1,6)

percent_cover_data$substring_location = 
  substr(percent_cover_data$location,1,6)

# We only want the year, not the month so create of substring of the year column. 
percent_cover_data <- percent_cover_data %>%
  separate(date, c("year", "month"), "-")

```


Select/Filter data 
```{r}
# Find the mean biomass of each species per year 
mean_biomass_species <- annual_fish_survey_data %>%
  filter(coarse_trophic == "Primary Consumer") %>% 
  group_by(year, taxonomy) %>%
  summarise(mean_biomass = mean(biomass))

# Select for only Macroalgae 
macroalgae_percent_cover_data <- percent_cover_data %>% 
  select(year, substring_location, macroalgae)

# Find the mean biomass each year
mean_biomass_per_year <- annual_fish_survey_data %>% 
  filter(coarse_trophic == "Primary Consumer") %>% 
  group_by(year) %>%
  summarise(mean_biomass = mean(biomass))

```


```{r}
# Plot biomass for site 
ggplot(data = mean_biomass_per_year, aes(x = year, y = mean_biomass, fill = "coral")) +
  geom_bar(stat = "identity", position = "identity") +
  guides(fill="none") +
  geom_vline(xintercept = 5, alpha = .8) +
  annotate("text", x = 5.8, y = 200, label = "Cyclone Oli", size = 3, alpha = .8) +
  annotate("rect", xmin = 1, xmax = 4, ymin = -Inf, ymax = Inf,
           alpha = .3, fill = "purple") +
  annotate("text", x = 2.5, y = 200, label = "Crown of Thorns
Outbreak", size = 3, colour = "black", alpha = .8) +
  labs(title = "Herbivorous Reef Fish - Annual Mean Biomass",
  subtitle = "Moorea, French Polynesia (2006-2021)",
       x = "Year",
       y = "Mean Fish Biomass (gm^2)") +
  theme_bw() +
  theme(plot.caption.position = "panel", plot.caption = element_text(hjust = 0)) +
  theme(plot.title = element_text(vjust = 1)) + # Change vertical position
  theme(plot.title=element_text(size=20))


```

